version: '3' # composeファイルのバーション指定
services:
  app: # service名
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    volumes:
      - ./:/go # マウントディレクトリ指定
    environment:
      - "GOPATH=/go"
      - "GO111MODULE=off" # モジュールはGOPATHを見に行く