up:
		docker-compose up -d
build:
		docker-compose build
stop:
		docker-compose stop
restart:
		docker-compose restart
down:
		docker-compose down
run:
		docker-compose exec app go run main.go
work:
		docker-compose exec app bash
mod1:
		docker-compose exec app go mod init github.com/akakuro43/go-app
mod2:
		docker-compose exec goapp go mod tidy